[package]
name = "decay_si_derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = "2.0.18"
quote = "1.0"
strum = "0.24"
strum_macros = "0.24"
proc-macro-error = "1.0"
proc-macro2 = "1.0"